// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOIdfRL77x-YoyvKWb3nL0hLTr24B8-9Q',
    appId: '1:319515418051:web:65ec17402e852dbea97176',
    messagingSenderId: '319515418051',
    projectId: 'myapp-project-c0d01',
    authDomain: 'myapp-project-c0d01.firebaseapp.com',
    storageBucket: 'myapp-project-c0d01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxzjdOBzKSq4kKJXHwAMKR7D5kaXWtO4',
    appId: '1:319515418051:android:93890034540d5c6ba97176',
    messagingSenderId: '319515418051',
    projectId: 'myapp-project-c0d01',
    storageBucket: 'myapp-project-c0d01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj2wDcFGj-bm4Kp-1zX9_-Ykbi5UQzcu4',
    appId: '1:319515418051:ios:cc71e39ac879ed98a97176',
    messagingSenderId: '319515418051',
    projectId: 'myapp-project-c0d01',
    storageBucket: 'myapp-project-c0d01.appspot.com',
    iosBundleId: 'com.example.counterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj2wDcFGj-bm4Kp-1zX9_-Ykbi5UQzcu4',
    appId: '1:319515418051:ios:d4f6824d45708a62a97176',
    messagingSenderId: '319515418051',
    projectId: 'myapp-project-c0d01',
    storageBucket: 'myapp-project-c0d01.appspot.com',
    iosBundleId: 'com.example.counterapp.RunnerTests',
  );
}
